#!/bin/bash

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
      . "$HOME/.bashrc"
    fi
fi

if [[ "${KUDU_DEVPI_INDEX}" != "" ]]; then
  # Specify which devpi-server index to use
  devpi use --set-cfg --pip-set-trusted=yes "${KUDU_DEVPI_INDEX}"
fi
if [[ "${KUDU_DEVPI_LOGIN}" != "" ]]; then
  # allow empty password
  devpi login --password "${KUDU_DEVPI_PASSWORD}" "${KUDU_DEVPI_LOGIN}"
fi

# for locally installed python packages
export PATH="${PATH}:${dojo_home}/.local/bin"

# Ensure that after bash login pwd is /dojo/work
cd ${dojo_work}
